import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { ruleIds } from "../src/features/openapi-diff/types";

const ROOT = fileURLToPath(new URL("../", import.meta.url));
const GOLDENS_ROOT = join(ROOT, "src/features/openapi-diff/goldens");
const TEST_ROOT = join(ROOT, "src/features/openapi-diff");
const OUTPUT = join(ROOT, "docs/rule-coverage.md");

function collectGoldenRuleIds() {
  const covered = new Set<string>();

  for (const scenario of readdirSync(GOLDENS_ROOT, { withFileTypes: true })) {
    if (!scenario.isDirectory()) {
      continue;
    }

    const expectedPath = join(GOLDENS_ROOT, scenario.name, "expected.json");

    if (!existsSync(expectedPath)) {
      continue;
    }

    const content = readFileSync(expectedPath, "utf8");

    for (const ruleId of ruleIds) {
      if (content.includes(`"${ruleId}"`)) {
        covered.add(ruleId);
      }
    }
  }

  return covered;
}

function collectTestMentionedRuleIds() {
  const covered = new Set<string>();
  const files = collectTsFiles(TEST_ROOT);

  for (const file of files) {
    const content = readFileSync(file, "utf8");

    for (const ruleId of ruleIds) {
      if (content.includes(ruleId)) {
        covered.add(ruleId);
      }
    }
  }

  return covered;
}

function collectTsFiles(directory: string): string[] {
  const entries = readdirSync(directory, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const fullPath = join(directory, entry.name);

    if (entry.isDirectory() && entry.name !== "goldens") {
      files.push(...collectTsFiles(fullPath));
      continue;
    }

    if (entry.isFile() && entry.name.endsWith(".ts")) {
      files.push(fullPath);
    }
  }

  return files;
}

function main() {
  const golden = collectGoldenRuleIds();
  const tests = collectTestMentionedRuleIds();
  const uncovered = ruleIds.filter((ruleId) => !golden.has(ruleId) && !tests.has(ruleId));

  const lines = [
    "# Rule Coverage Matrix",
    "",
    `Generated by \`pnpm audit:rules\` on ${new Date().toISOString().slice(0, 10)}.`,
    "",
    "| Rule ID | Golden | Unit/integration test |",
    "| --- | --- | --- |",
    ...ruleIds.map((ruleId) => {
      return `| \`${ruleId}\` | ${golden.has(ruleId) ? "yes" : "no"} | ${tests.has(ruleId) ? "yes" : "no"} |`;
    }),
    "",
    "## Uncovered rules",
    "",
    uncovered.length === 0
      ? "All rule IDs are referenced by at least one golden snapshot or test file."
      : uncovered.map((ruleId) => `- \`${ruleId}\``).join("\n"),
    "",
  ];

  writeFileSync(OUTPUT, lines.join("\n"));
  console.log(`Wrote ${OUTPUT}`);
  console.log(`Uncovered: ${uncovered.length}`);

  if (uncovered.length > 0) {
    process.exitCode = 1;
  }
}

main();
